name: 03 - Workflow Runners

on: 
  push
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo runner info 
        run: |
          echo "This job is running on an ubuntu runner."
          echo "Runner OS: $RUNNER_OS"