name: 08 - Using Variables

on: 
  push:
  workflow_dispatch:
env:
  workflow_var: 'I am a workflow var'


jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
    steps:
      - name: Print Env Variables
        env:
          step_var: 'I am a step env var'
          step_var2: 'I am another step env var'
        run: |
          echo "Step env var: ${{env.step_var}}"  
          echo "Step env var2: $step_var2"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "workflow env var: ${{env.workflow_var}}"